[[plugins]]
  package = "@netlify/plugin-gatsby"
[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_VERSION = "9.6.4"
  NPM_FLAGS = "--legacy-peer-deps"
